### ISSUE TITLE
cannot import name 'BaseLanguageModel' from 'langchain.schema'

### ISSUE THREAD

**Issue by beddows** [PrefectHQ/langchain-prefect#21]
I'm getting the following error when using "from langchain_prefect.plugins import RecordLLMCalls" (with langchain 0.0.166) when running langchain agent as Prefect subflows:

Traceback (most recent call last):
  File "/dev/query-test.py", line 2, in <module>
    from langchain_prefect.plugins import RecordLLMCalls
  File "miniconda3/envs/langchain/lib/python3.10/site-packages/langchain_prefect/plugins.py", line 7, in <module>
    from langchain.schema import BaseLanguageModel, LLMResult
ImportError: cannot import name 'BaseLanguageModel' from 'langchain.schema' (miniconda3/envs/langchain/lib/python3.10/site-packages/langchain/schema.py)

**Comment by CameronVetter** [comment]
Same here with langchain 0.0.189

**Comment by zzstoatzz** [comment]
hi @CameronVetter and @beddows - pushed a fix and released, they moved the import

but I would encourage you to check out https://github.com/PrefectHQ/marvin instead, we've done a lot of work to achieve observability using langchain LLMs (plus a lot of other things 🙂 )

honestly that's where my focus is at this time
